Script started on Fri 09 Apr 2021 10:44:17 AM CDT
[?1034hbash-4.2$ ./project5_c[KCarter_sc[Klc0070
Banner id: 904059558
producer produce item 7
consumer consume item 7
producer produce item 14
consumer consume item 14
producer produce item 21
consumer consume item 21
producer produce item 28
consumer consume item 28
producer produce item 35
consumer consume item 35
producer produce item 42
consumer consume item 42
producer produce item 49
consumer consume item 49
producer produce item 56
consumer consume item 56
producer produce item 63
consumer consume item 63
producer produce item 70
consumer consume item 70
bash-4.2$ exit
exit

Script done on Fri 09 Apr 2021 10:45:31 AM CDT
